### ISSUE TITLE
mod failed to load correctly

### ISSUE THREAD

**Issue by borealisbaran** [Edivad99/ExtraStorage#13]
when try to load the modpack (direwolf20 1.16.4) an error shows up saying extra storage mod failed to load correctly 
net.minecraft.util.ResourceLocationExpection: Non [a-z0-9/._-] character in the path of location: extrastorageıron_crafter
i tried to load without the mod and modpack worked properly 

Mod version:ExtraStorage-1.16.4-1.2.1
Forge version:1.16.4-forge-35.1.13
Minecraft version:1.16.4
Refined Storage version:1.9.9
Are you playing on server?:no

**To Reproduce**
1.downgraded the mod
2.deleted it

![Screenshot_431](https://user-images.githubusercontent.com/76411985/102727595-80513500-4337-11eb-9706-266f28ea10d6.png)

**Comment by Edivad99** [comment]
With the following configurations:
Mod version: ExtraStorage-1.16.4-1.2.1
Forge version: 1.16.4-forge-35.1.13
Minecraft version: 1.16.4
Refined Storage version: 1.9.9

I only installed the Refined Storage and the ExtraStorage and I have no problem.
Can you send me the debug.log file via pastebin?

**Comment by borealisbaran** [comment]
i fixed it there was a problem with the language of my computer when i made it english there was no problem!

**Comment by KeremKoksal** [comment]
> 
> 
> i fixed it there was a problem with the language of my computer when i made it english there was no problem!

But this is not a fix! Why should I change my computers language just to be able to use this mod? 

I think the problem would be fixed by using lower case variable names. I think you have used IRON_CRAFTER or Iron_crafter as a variable name and it becomes ıron_crafter instead of iron_crafter on loading. I don't know how minecraft mods or forge work but this is the only logical explanation that I can think of.

**Comment by Edivad99** [comment]
If you look at the code I only use lowercase letters, which is why I still don't understand how the hell that error is generated. Also all the characters I use to define the block resource name are valid.

**Comment by KeremKoksal** [comment]
I think there is a problem with FTB App. I was checking out Direwolf20 modpack. I had the problem when loading it with FTB App but then I've moved it to MultiMC and it had loaded without a problem. I think I had a similar problem with twitch app too. 
But, it still bugs me why this mod has a problem and not others. Don't they have any variables that has "i" :)

A very bad advise to fix the problem: remove any "i" form your variables 😅

Or just close the issue and mark it as a modpack loader app problem. But, there must be a way to fix it because there are mods that don't have this problem.

**Comment by Edivad99** [comment]
Can you check if this bug is still present with the new update?
I tried to insert the values directly into the code, maybe there was a problem with the toLowerCase() function...
https://www.curseforge.com/minecraft/mc-mods/extrastorage/files/3160541

**Comment by KeremKoksal** [comment]
It works with the ftb app now! There is certainly a problem with toLowerCase function. It works with localization. If you don't point out the desired locale, it uses systems locale. In my case; "IRON_CRAFTER" to "ıron_case" which has a non English character "ı". You can refer to this page: https://stackoverflow.com/questions/11063102/using-locales-with-javas-tolowercase-and-touppercase

**Comment by Edivad99** [comment]
This thing I did not know, great! Thanks for the feedback
