### ISSUE TITLE
[1.16.3] Buttons don't work in advanced exporter, no crafter mode for crafters

### ISSUE THREAD

**Issue by WhitePhant0m** [Edivad99/ExtraStorage#3]
**Describe the bug**
Buttons don't work in advanced exporter, no crafter mode for crafters

**Configuration**
Mod version: ExtraStorage-1.16.3-1.0.1
Forge version: 34.1.1
Minecraft version: 1.16.3
Refined Storage version: refinedstorage-1.9.7
Are you playing on server?: Yes

**To Reproduce**
Steps to reproduce the behavior(advanced exporter):
1. Click any button
2. Notice that they don't do anything

**Expected behavior**
For the buttons to do stuff and for the crafters to have crafter mode buttons

**Screenshots**
![image](https://user-images.githubusercontent.com/33400200/95024140-e52ab680-0689-11eb-9ab7-dbd65d35456d.png)
![image](https://user-images.githubusercontent.com/33400200/95024146-f247a580-0689-11eb-8917-9a3287aceb70.png)

**Comment by Edivad99** [comment]
### Small update: 
I added the buttons on the crafter.
I found that on the first access to the server there are no problems, from the second access onwards the server crashes.
I'm investigating to see if it is a problem to use RS packages to update my tileentities, it may take some time.
On the client this problem is not present.

**Comment by Edivad99** [comment]
Forget it, I fixed the bug :laughing:
