### ISSUE TITLE
Conflict with recipes with Extra Disks

### ISSUE THREAD

**Issue by lacomarca** [Edivad99/ExtraStorage#8]
**Describe the bug**
I have Extra Disks and your mod and both are amazing. Nevertheless, I can't create more than 256k disks because there is a conflict with your mod recipes (I'm trying to automate the process with patterns).

Hope these screenshots could help:

https://gyazo.com/68bfed016d4aa695cdac61b061d2ce13
https://gyazo.com/f4d260c2f8aa33b85005b4dc5f65ff04

**Configuration**
Mod version: ExtraStorage-1.16.3-1.1.0
Forge version: 34.1.19
Minecraft version: 1.16.3
Refined Storage version: refinedstorage-1.9.7
Are you playing on server?: yes

**To Reproduce**
1. Try to create a disk
2. I can't create some parts needed in other mod because there is a conflict with your recipe (other mod told me to contact you).

**Expected behavior**
ThatI could create disks more than 64k with other mod with no conflicts.

**Screenshots**
https://gyazo.com/68bfed016d4aa695cdac61b061d2ce13
https://gyazo.com/f4d260c2f8aa33b85005b4dc5f65ff04

**Additional context**
Hope you can work on this so I can use both mods :) Thanks a lot in advance!

**Comment by Edivad99** [comment]
Unfortunately you have to choose which mod to keep. The recipes for the disks are the same as for ExtraDisk because we both took the cells from the Reborn Storage. Since my mod also adds the various storage blocks I didn't want to create a tight dependency on ExtraDisk. The disks that my mod adds work like ExtraDisk's disks.
